services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STEAM_PROFILE_URL=${STEAM_PROFILE_URL}
      - STEAM_GAMES_URL=${STEAM_GAMES_URL}
      - STEAM_MEDIA_URL=${STEAM_MEDIA_URL}
    restart: unless-stopped
